### PR TITLE
migrated from xproj to csproj

### PR DESCRIPTION
**Pull request by dannyb2100**
Updated the project.json as the "dotnet migrate" command doesn't like '*'

### CODE REVIEW

**Comment by jcurl** [comment]
Any idea why I get a bunch of warning messages?

```
C:\Users\jcurl\Documents\Programming\SerialPortStream>dotnet restore code\netstandard\netstandard.csproj
  Restoring packages for C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Collections from 4.3.0 to 4.0.11 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Collections (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Collections (>= 4.0.11) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Diagnostics.Debug from 4.3.0 to 4.0.11 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Diagnostics.Debug (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Diagnostics.Debug (>= 4.0.11) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Diagnostics.Tools from 4.3.0 to 4.0.1 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Diagnostics.Tools (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Diagnostics.Tools (>= 4.0.1) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.IO from 4.3.0 to 4.1.0 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.IO (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.IO (>= 4.1.0) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.IO.FileSystem from 4.3.0 to 4.0.1 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.IO.FileSystem (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.IO.FileSystem (>= 4.0.1) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Runtime.Extensions from 4.3.0 to 4.1.0 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Runtime.Extensions (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Runtime.Extensions (>= 4.1.0) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Runtime.Handles from 4.3.0 to 4.0.1 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Runtime.Handles (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Runtime.Handles (>= 4.0.1) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Runtime.InteropServices (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Runtime.InteropServices (>= 4.1.0) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Runtime.InteropServices.RuntimeInformation from 4.3.0 to 4.0.0.0 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Runtime.InteropServices.RuntimeInformation (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Runtime.InteropServices.RuntimeInformation (>= 4.0.0) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Text.Encoding from 4.3.0 to 4.0.11 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Text.Encoding (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Text.Encoding (>= 4.0.11) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Threading from 4.3.0 to 4.0.11 \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> NETStandard.Library (>= 1.6.1) -> System.Threading (>= 4.3.0) \r [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  netstandard (>= 2.1.2) -> System.Threading (>= 4.0.11) [C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj]
  Generating MSBuild file C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\obj\netstandard.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\obj\netstandard.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\obj\project.assets.json
  Restore completed in 1.39 sec for C:\Users\jcurl\Documents\Programming\SerialPortStream\code\netstandard\netstandard.csproj.

  NuGet Config files used:
      C:\Users\jcurl\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
```

I installed the command line tools of .NET Core 1.0.4 to test this.

**Comment by dannyb2100** [comment]
WIthin `netstandard.csproj`

The   
 +    <PackageReference Include="System.Threading.Overlapped" Version="4.0.1" />

I assume it's due to the fact it's an older version than what you were using? I am not 100% sure, I didn't get any errors when migrating?

**Comment by jcurl** [comment]
Can you provide details how you did the migration? I used dotnet migrate with 1.0.4 and got an exception. When I update the content of the csproj with the content in the nuspec the errors go away

**Comment by jcurl** [comment]
Reworked and merged the pull request with 4e0056039b677940ec36ed78d070ae340096d0ac

**Pull request closed without merging**
